
```{r}
source("https://raw.githubusercontent.com/tpemartin/110-2-R/main/R/traffice-accidents2.R")
```

```{r}

within(
  traffic,
  {
    hour <- factor(hour)
    縣市 <- factor(縣市)
    
    發生時間 |> lubridate::wday() -> wday
    isWeekend = (wday %in% c(1,7))
  }
) -> traffic

hourWeekend <- factor(traffic$hour):factor(traffic$isWeekend)
hourWeekend

traffic |> split(hourWeekend) -> split_traffic

dataFrame_byHour_byCounty <- data.frame(
  時段=character(0),
  週末=character(0),
  總車禍次數=integer(0),
  時段車禍縣市數目=integer(0),
  縣市=character(0),
  時段名次=character(0)
)
.x=1
for(.x in seq_along(split_traffic)){
  split_traffic[[.x]]$縣市 |>
    table() |> 
    sort(decreasing = T) -> accidents_hourX
  splitX = split_traffic[[.x]]
  data.frame(
    時段=splitX$hour[[1]],
    週末=splitX$isWeekend[[1]],
    總車禍次數=nrow(splitX),
    時段車禍縣市數目=length(accidents_hourX[accidents_hourX!=0]),
    車禍次數=as.integer(accidents_hourX),
    縣市=names(accidents_hourX),
    時段名次=length(accidents_hourX)+1-rank(accidents_hourX,
    ties.method = "first")
    
  ) -> dataFrameOfHourX
  
  dataFrame_byHour_byCounty <- 
    rbind(dataFrame_byHour_byCounty,
      dataFrameOfHourX)
  
}

```
