
```{r}
example2 <- c("John", "Mary", "Bill", person4="Jack")
```

```{r}
example2[c(1, 2, 3)]
```

```{r}
example2 <- c("John", "Mary", "Bill", person4="Jack")
example2 <- example2[1:3]
example2 <- example2[c(1, 2, 3)]
```

```{r}
c(1, 2, 3)
1:3
```

```{r}
7:11
```

```{r}
2:-1
```

```{r}
2:12
seq(from=2, to=12)
```

```{r}
seq(from=2, to=12, by=0.01)
seq(2, 12, 0.01)
seq(from=2, to=12, length.out=13)
# 等分13-1格
seq(from=2, to=12, length.out=2)
seq(length.out=2, to=12, from=2)
seq(2, 12, length.out=2)
# 1 格

```

```{r}
example2Copy <- example2 <- c("John", "Mary", "Bill", person4="Jack")
example2Copy <- example2Copy[c(1,2,3)]
example2Copy
example2Copy <- example2
example2Copy <- example2Copy[1:3]
example2Copy
example2Copy <- example2
example2Copy <- example2Copy[seq(1,3)]
```

```{r}
example2Copy <- example2
example2Copy <- example2Copy[c(1,3)]
```

```{r}
example2Copy <- example2
example2Copy <- example2Copy[-c(2,4)]
example2Copy[c(-2, -4)]
```

```{r}
sample(LETTERS, 15, T) -> example3
example3
```

```{r}
example3 <- example3[-(3:7)]
example3
```


```{r}
example4 <- c("John", "Mary", "Bill", person4="Jack")
names(example4) # 查詢目前元素名稱
names(example4)[1:3] <- c("a", "b", "c")
names(example4) <- c("a", "b", "c")

names(example4)[1:3] <- c("a", "b", "c") 
names(example4) <- c("a", "b", "c")
names(example4)[1:4] <- c("a", "b", "c", "person4")

example4[c(1:3)] -> example4
example4[-4] -> example4
# example4[-'person4']

# Object source <- retrieval of elements to keep
example4 <-
  example4[-c(4)]

example4
```

```{r}
JohnsFamily <-
  list(
    name = "John", 
    age = 35,
    spouse = list(
      name = "Mary", 
      age = 32),
    children = list(
      list(
        name = "Bill", 
        age = 5),
      list(
        name = "Jane", 
        age = 3)
    )
  )
```

```{r}
JohnsFamilyCopy5 <- JohnsFamilyCopy6 <- JohnsFamilyCopy7 <- JohnsFamilyCopy8 <-  JohnsFamily
```


```{r}
example4
example4[[4]] <- ""
example4
```

```{r}
example4[[4]] <- NULL
```

```{r}
example5 <- list("John", "Mary", "Bill", person4="Jack")
```

```{r}
# 去掉1-3的元素後回存
example5[-(1:3)] -> example5
# 把1-3的元素值設為虛空
example5[1:3] <- NULL
example5[4] -> example5
example5
```

```{r}
example5[4]
example5[[4]] -> example5
example5
```

```{r}
exmaple
```



```{r}
example5[1:3] <- NULL
example5
```


```{r}
example5[[4]] <- NULL
example5
```

```{r}
JohnsFamilyCopy5
JohnsFamilyCopy5$spouse$age <- 33
JohnsFamilyCopy5$spouse <- NULL
JohnsFamilyCopy5
JohnsFamilyCopy5$children[[2]] <- NULL

```

```{r}
httr::GET("https://data.taipei/api/v1/dataset/91290609-2b8b-4130-8ce9-e6085529bc46?scope=resourceAquire
") -> mydata0
```

```{r}
httr::GET("https://data.taipei/api/v1/dataset/91290609-2b8b-4130-8ce9-e6085529bc46?scope=resourceAquire&resource_id=91290609-2b8b-4130-8ce9-e6085529bc46&limit=1000") -> mydata0
httr::content(mydata0) -> mydata1
```

```{r}
mrtStationAds <- 
  httr::content(
    httr::GET("https://data.taipei/api/v1/dataset/91290609-2b8b-4130-8ce9-e6085529bc46?scope=resourceAquire&limit=1000")
    )
```



```{r}
saveRDS(mydata1, file="mydata1.Rds")
```

```{r}
mydata1 <- readRDS(file="mydata1.Rds")
```







